### PR TITLE
feature/placeholderCopyPaste

### PR DESCRIPTION
**Pull request by Naveen-ux**
1. Add placeholder to the input field by config value.
2. Detect paste from input field & set value.

### CODE REVIEW

**Comment by Naveen-ux** [comment]
@code-farmz @DenysDzhel We added new two features in ng-otp-input, input field placeholder from config and detect  input field paste value and fill the pasted value.

**Comment by Naveen-ux** [comment]
@code-farmz @DenysDzhel This changes helps you to add new feature like input placeholder and detect input field paste and fill the value.

**Comment by code-farmz** [comment]
@Naveen-ux  will look into it and will merge if everything works fine

**Comment by Naveen-ux** [comment]
@code-farmz Thanks.

**Comment by meyyappanv** [comment]
@code-farmz Could you please help here with an approx ETA? Thanks in advance. Merry Christmas and Happy new year :)

**Comment by code-farmz** [comment]
@Naveen-ux  your changes has been merged and published with some modification refer to #25

**Comment by code-farmz** [comment]
> @code-farmz Could you please help here with an approx ETA? Thanks in advance. Merry Christmas and Happy new year :)

this is done now

**Comment by meyyappanv** [comment]
Thanks @code-farmz. :)

**Pull request closed without merging**
