### PR TITLE
added NgOtpInputComponent to public_api

### PR DESCRIPTION
**Pull request by vorant94**

### CODE REVIEW

**Comment by code-farmz** [comment]
this commit doesn't make any functional difference or bug fix.I will consider it in a future release. Thanks for your contribution.

**Comment by vorant94** [comment]
Hi, once again. I am not sure my change has no functional difference. Right now I can access your component with help of 'ViewChild' only by assigning it some reference and also I have no type support as you showed in example in README

'''
@ViewChild('ngOtpInput') ngOtpInputRef:any;
'''

But if you make public component itself, this will give the opportunity to use next syntax

'''
@ViewChild(NgOtpInputComponent) ngOtpInputRef: NgOtpInputComponent;
'''

Like you see in [angular doc example](https://angular.io/api/core/ViewChild#example-2)

**Comment by vorant94** [comment]
@code-farmz no response for my previous comment?

**Comment by code-farmz** [comment]
@vorant94  sorry, I missed it. I have implemented the same while moving it to angular 12 and will publish it soon.

**Pull request closed without merging**
